CREATE USER 'bd_adm'@'%' IDENTIFIED BY 'L^ud~O\0Yt$uo.@:]qm}Jf_!27YzS.NP';
CREATE USER 'support'@'%' IDENTIFIED BY 'vkyY+2zWGvHcy2WY=cM^HF6qee8j+jy/';
CREATE USER 'api_config'@'%' IDENTIFIED BY 'ETQ]X{Fs.0e!_^%Mc3O#[Rm%-<k]sjSv';
CREATE USER 'api_results'@'%' IDENTIFIED BY 'U:wQyr=8+b>pwpv{FE\o6nBo~;J-}h&u';
CREATE USER 'api_auth'@'%' IDENTIFIED BY '@;+9#hz_T.Ut>K&1Q>>GLj6s[7LgzcR0';

GRANT ALL PRIVILEGES ON *.* TO 'bd_adm'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON AD TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON ADDRESS TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON ASOC TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON ASOC_ADDRESS TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON ASOC_PLYR TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON ASOC_SPO TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON EVENT TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON EVENT_ADDRESS TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON EVENT_FAMILY TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON EVENT_SPO TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON FAMILY TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON FOULS TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON JUD_ADD TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON JUD_FOUL TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON JUDGE TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON MANA_ASOC TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON MANA_PLYR TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON MANA_SPO TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON MANA_TEAM TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON MANAGER TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON PHONES TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON PLAYER TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON PLAYER_SPO TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON PLYR_ADDRESS TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON PLYR_TM TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON PLYR_TM_TI_SC TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON PLYR_TM_TIME_FL TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON SC_ASOC TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON SCORE TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON T_SPO TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON TEAM TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON TEAM_ADDRESS TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON TIME TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON TM_ASOC TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON TM_SPO TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON TMTI TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON USER TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON USER_ADDRESS TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON USER_SUB_ASOC TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON USER_SUB_FAM TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON USER_SUB_MANA TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON USER_SUB_PLYR TO 'support'@'%';
GRANT SELECT, INSERT, DELETE, UPDATE ON USER_SUB_SPO TO 'support'@'%';
GRANT SELECT INSERT PRIVILEGES ON USER TO 'api_auth'@'%';
GRANT SELECT PRIVILEGES ON ASOC TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON ASOC_ADDRESS TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON ADDRESS TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON ASOC_PLYR TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON ASOC_SPO TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON EVENT TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON EVENT_ADDRESS TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON EVENT_SPO TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON EVENT_FAMILY TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON FAMILY TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON FOULS TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON JUD_ADD TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON JUD_FOUL TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON JUDGE TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON MANA_ASOC TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON MANA_PLYR TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON MANA_SPO TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON MANA_TEAM TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON MANAGER TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON PHONES TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON PLAYER TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON PLAYER_SPO TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON PLYR_ADDRESS TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON PLYR_TM TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON PLYR_TM_TI_SC TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON PLYR_TM_TIME_FL TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON SC_ASOC TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON SCORE TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON SPORT TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON T_SPO TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON TEAM TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON TEAM_ADDRESS TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON TIME TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON TM_ASOC TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON TM_SPO TO 'api_results'@'%'
GRANT SELECT PRIVILEGES ON TMTI TO 'api_results'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON USER TO 'api_config'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON USER_ADDRESS TO 'api_config'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON ADDRESS TO 'api_config'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON USER_SUB_ASOC TO 'api_config'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON USER_SUB_FAM TO 'api_config'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON USER_SUB_MANA TO 'api_config'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON USER_SUB_PLYR TO 'api_config'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON USER_SUB_SPO TO 'api_config'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON PHONES TO 'api_config'@'%'
GRANT SELECT, INSERT, DELETE, UPDATE  ON PAYMENT TO 'api_config'@'%'



Tenes que poner cada una de las tablas para support
Cambiar % por %