CREATE USER 'bd_adm'@'localhost' IDENTIFIED BY 'L^ud~O\0Yt$uo.@:]qm}Jf_!27YzS.NP';
CREATE USER 'support'@'localhost' IDENTIFIED BY 'vkyY+2zWGvHcy2WY=cM^HF6qee8j+jy/';
CREATE USER 'api_config'@'localhost' IDENTIFIED BY 'ETQ]X{Fs.0e!_^%Mc3O#[Rm%-<k]sjSv';
CREATE USER 'api_results'@'localhost' IDENTIFIED BY 'U:wQyr=8+b>pwpv{FE\o6nBo~;J-}h&u';
CREATE USER 'api_auth'@'localhost' IDENTIFIED BY '@;+9#hz_T.Ut>K&1Q>>GLj6s[7LgzcR0';

GRANT ALL PRIVILEGES ON *.* TO 'bd_adm'@'localhost';
GRANT ALL PRIVILEGES ON OLYMPUS.* TO 'support'@'localhost';
GRANT SELECT INSERT PRIVILEGES ON OLYMPUS.USER TO 'api_auth'@'localhost';
GRANT SELECT PRIVILEGES ON ASOC TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON ASOC_ADDRESS TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON ADDRESS TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON ASOC_PLYR TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON ASOC_SPO TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON EVENT TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON EVENT_ADDRESS TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON EVENT_SPO TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON EVENT_FAMILY TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON FAMILY TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON FOULS TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON JUD_ADD TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON JUD_FOUL TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON JUDGE TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON MANA_ASOC TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON MANA_PLYR TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON MANA_SPO TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON MANA_TEAM TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON MANAGER TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON PAYMENT TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON PHONES TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON PLAYER TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON PLAYER_SPO TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON PLYR_ADDRESS TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON PLYR_TM TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON PLYR_TM_TI_SC TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON PLYR_TM_TIME_FL TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON SC_ASOC TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON SCORE TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON SPORT TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON T_SPO TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON TEAM TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON TEAM_ADDRESS TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON TIME TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON TM_ASOC TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON TM_SPO TO 'api_results'@'localhost'
GRANT SELECT PRIVILEGES ON TMTI TO 'api_results'@'localhost'
GRANT ALL PRIVILEGES ON USER TO 'api_config'@'localhost'
GRANT ALL PRIVILEGES ON USER_ADDRESS TO 'api_config'@'localhost'
GRANT ALL PRIVILEGES ON ADDRESS TO 'api_config'@'localhost'
GRANT ALL PRIVILEGES ON USER_SUB_ASOC TO 'api_config'@'localhost'
GRANT ALL PRIVILEGES ON USER_SUB_FAM TO 'api_config'@'localhost'
GRANT ALL PRIVILEGES ON USER_SUB_MANA TO 'api_config'@'localhost'
GRANT ALL PRIVILEGES ON USER_SUB_PLYR TO 'api_config'@'localhost'
GRANT ALL PRIVILEGES ON USER_SUB_SPO TO 'api_config'@'localhost'
GRANT ALL PRIVILEGES ON PHONES TO 'api_config'@'localhost'
GRANT ALL PRIVILEGES ON PAYMENT TO 'api_config'@'localhost'
