"SELECT * FROM Ad";

"SELECT * FROM User LEFT JOIN phones ON User.Id = phones.Id_User "; 

"SELECT * FROM AD WHERE id = @id";

"UPDATE AD SET " + 
                 "PATH = @PATH," + 
                 "CAT = @CAT " + 
                 "AD_NAME = @AD_NAME " + 
                  "WHERE id = @id";

"INSERT INTO " + 
                    "AD (PATH,CAT,AD_NAME) " + 
                    "VALUES (@PATH,@CAT,@AD_NAME)";

SELECT FAMILY.NAME , FAMILY.RECURRENCY, FAMILY.DOMAIN, FAMILY.TYPE, FAMILY.PARENT_ID, EVENT.NAME, EVENT.DATE, TEAM.NAME, TEAM.IS_ASSOCIATED, PLAYER.NAME, PLAYER.LNAME1, PLAYER.LNAME2, PLAYER.STATUS, PLAYER.AGE, SCORE.TYPE, SCORE.QUANTITY, SCORE.CONTEXT, FOULS.TYPE, FOULS.QUANTITY, FOULS.CONTEXT, JUDGE.NAME, JUDGE.LNAME1, JUDGE.LNAME2
FROM OLYMPUS.EVENT STRAIGHT_JOIN (TIME, TMTI, TEAM, PLYR_TM, PLAYER, PLYR_TM_TI_SC, PLYR_TM_TIME_FL, SCORE, FOULS, JUDGE, JUD_FOUL, FAMILY, EVENT_FAMILY)
ON (EVENT.ID = TIME.ID_EVENT AND TIME.ID = TMTI.ID_TIME AND TMTI.ID_TEAM = TEAM.ID AND PLYR_TM.ID_TEAM = TEAM.ID AND PLYR_TM.ID_PLYR = PLAYER.ID AND TIME.ID = PLYR_TM_TI_SC.ID_TIME AND TEAM.ID = PLYR_TM_TI_SC.ID_TEAM AND SCORE.ID = PLYR_TM_TI_SC.ID_SC AND PLYR_TM_TIME_FL.ID_TIME = TIME.ID AND PLYR_TM_TIME_FL.ID_TEAM = TEAM.ID AND PLYR_TM_TIME_FL.ID_FL = FOULS.ID AND JUD_FOUL.ID_FL = FOULS.ID AND JUD_FOUL.ID_JUD = JUDGE.ID) ;

"SELECT * FROM AD WHERE id = @id"; 

 "SELECT * FROM AD WHERE Ad_Name = @Ad_Name";

"SELECT * FROM user WHERE id = @id";

"SELECT * FROM phones WHERE id_user = @id";

"SELECT * FROM User WHERE UNAME = @UNAME";

"SELECT * FROM User";


CREATE TABLE AD(
    ID INT(8) UNSIGNED auto_increment,
    NAME VARCHAR(60),
    CAT VARCHAR(40) NOT NULL,
    PATH VARCHAR(150) NOT NULL,
    primary key(ID, NAME));


INSERT INTO " +
                   "User (NAME,LNAME1,LNAME2,EMAIL,UNAME,PASS,ROLE) " +
                   "VALUES (@Name,@Lastname1,@Lastname2,@Email,@Username,@Password,@UserRole)

INSERT INTO " +
                   "phones (id_user,num) " +
                   "VALUES (@id_user,@Num)

UPDATE user SET " +
                "NAME = @Name," +
                "LNAME1 = @Lastname1," +
                "LNAME2 = @Lastname2," +
                "EMAIL = @Email," +
                "UNAME = @Username," +
                "PASS = @Password," +
                "ROLE = @UserRole " +
                 "WHERE id = @id;

DELETE FROM user WHERE id = @id

SELECT UNAME,PASS FROM user WHERE UNAME = @UserName

SELECT NAME,LNAME1,LNAME2,EMAIL,UNAME,PASS,ROLE FROM user WHERE UNAME = @UNAME

SELECT ID_USER,NUM FROM phones WHERE ID_USER = @ID_USER", "ID_USER

SELECT id,UserName FROM User

SELECT * FROM User LEFT JOIN phones ON User.Id = phones.Id_User

SELECT PLAYER.NAME, PLAYER.LNAME1, PLAYER.LNAME2, PLAYER.STATUS, PLAYER.AGE FROM PLAYER WHERE PLAYER.NAME = @PlayerName

SELECT FAMILY.NAME , FAMILY.RECURRENCY, FAMILY.DOMAIN, " +
                "FAMILY.TYPE, FAMILY.PARENT_ID, EVENT.NAME, EVENT.DATE, TEAM.NAME, PLAYER.NAME, " +
                "PLAYER.LNAME1, PLAYER.STATUS, PLAYER.AGE, SCORE.TYPE, SCORE.QUANTITY, " +
                "SCORE.CONTEXT, FOULS.TYPE, FOULS.QUANTITY, FOULS.CONTEXT, JUDGE.NAME, JUDGE.LNAME1 " +
                "FROM OLYMPUS.EVENT STRAIGHT_JOIN(TIME, TMTI, TEAM, PLYR_TM, " +
                "PLAYER, PLYR_TM_TI_SC, PLYR_TM_TIME_FL, SCORE, FOULS, JUDGE, JUD_FOUL, FAMILY, EVENT_FAMILY) " +
                "ON(EVENT.ID = TIME.ID_EVENT AND TIME.ID = TMTI.ID_TIME AND TMTI.ID_TEAM = TEAM.ID " +
                "AND PLYR_TM.ID_TEAM = TEAM.ID AND PLYR_TM.ID_PLYR = PLAYER.ID AND TIME.ID = PLYR_TM_TI_SC.ID_TIME " +
                "AND TEAM.ID = PLYR_TM_TI_SC.ID_TEAM AND SCORE.ID = PLYR_TM_TI_SC.ID_SC AND PLYR_TM_TIME_FL.ID_TIME = TIME.ID " +
                "AND PLYR_TM_TIME_FL.ID_TEAM = TEAM.ID AND PLYR_TM_TIME_FL.ID_FL = FOULS.ID " +
                "AND JUD_FOUL.ID_FL = FOULS.ID AND JUD_FOUL.ID_JUD = JUDGE.ID) WHERE EVENT.NAME = @EventName

SELECT FAMILY.NAME ," +
                " EVENT.NAME ," +
                " SCORE.QUANTITY ," +
                " TEAM.NAME FROM OLYMPUS.EVENT STRAIGHT_JOIN ( TIME, TMTI, TEAM, PLYR_TM_TI_SC, SCORE, EVENT_FAMILY, FAMILY) ON " +
                "(EVENT.ID = TIME.ID_EVENT AND TMTI.ID_TIME = TIME.ID AND TMTI.ID_TEAM = TEAM.ID AND PLYR_TM_TI_SC.ID_TIME = TIME.ID AND PLYR_TM_TI_SC.ID_TEAM" +
                " = TEAM.ID AND PLYR_TM_TI_SC.ID_SC = SCORE.ID AND EVENT.ID = EVENT_FAMILY.ID_EVENT AND EVENT_FAMILY.ID_FAM = FAMILY.ID) LIMIT 5000;

"INSERT INTO" +
                   "event (EventName,Date,PreEvent) " +
                   "VALUES (@EventName,@Date,@PreEvent)";
"UPDATE user SET " +
                "EventName = @EventName," +
                "Date = @Date," +
                "PreEvent = @PreEvent," +
                 "WHERE ID = @ID";
"SELECT * FROM event";
"SELECT * FROM asoc"